name: "Keep services on by pinging"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  keep_fin_render_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "cUrl"
        run: 'curl -X POST -H "token: ${{ secrets.API_TOKEN }}" "${{ secrets.API_URL }}/budget"'